sonar.projectKey=raheenzia_cohort-9-mern-13791-raheen
sonar.organization=raheenzia


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=cohort-9-mern-13791-raheen
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/.git/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8